apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-service-account
  namespace: microservices

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-role
  namespace: microservices
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-role-binding
  namespace: microservices
subjects:
- kind: ServiceAccount
  name: app-service-account
  namespace: microservices
roleRef:
  kind: Role
  name: app-role
  apiGroup: rbac.authorization.k8s.io
