apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-backup-cronjob
  namespace: microservices
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mysql-backup
            image: mysql:8
            command:
            - /bin/bash
            - -c
            - |
              echo "Starting MySQL backup..."
              BACKUP_DATE=$(date +%Y-%m-%d_%H-%M-%S)
              BACKUP_FILE="microservices_db_backup_$BACKUP_DATE.sql"
              
              # Create backup directory
              mkdir -p /backup
              
              # Perform database backup
              mysqldump -h mysql-service-external -u root -p$MYSQL_ROOT_PASSWORD \
                --single-transaction \
                --routines \
                --triggers \
                --databases microservices_db > /backup/$BACKUP_FILE
              
              if [ $? -eq 0 ]; then
                echo "Backup completed successfully: $BACKUP_FILE"
                
                # Compress the backup
                gzip /backup/$BACKUP_FILE
                echo "Backup compressed: $BACKUP_FILE.gz"
                
                # Clean up old backups (keep last 7 days)
                find /backup -name "*.gz" -type f -mtime +7 -delete
                echo "Old backups cleaned up"
                
                # List current backups
                echo "Current backups:"
                ls -la /backup/
              else
                echo "Backup failed!"
                exit 1
              fi
            env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            volumeMounts:
            - name: backup-storage
              mountPath: /backup
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: mysql-backup-pvc
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-backup-pvc
  namespace: microservices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi