apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-sa
  namespace: microservices

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-cr
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics", "/metrics/cadvisor"]
  verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-crb
subjects:
- kind: ServiceAccount
  name: prometheus-sa
  namespace: microservices
roleRef:
  kind: ClusterRole
  name: prometheus-cr
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus-service # This is the name for your new service
  namespace: microservices
  labels:
    app: prometheus # This label should match the label on your prometheus deployment
spec:
  selector:
    app: prometheus # This MUST match the label on your prometheus pod
  ports:
    - protocol: TCP
      port: 9090       # The port the service will be available on inside the cluster
      targetPort: 9090 # The port the prometheus container is listening on